---
name: 'Fix a Bug '
about: An Issue Template to help you know about creating issue.
title: "[BUG]:  <Your-issue-title>"
labels: bug
assignees: ''

---

<!-- You have to properly follow the criteria below -->


### What bug do you want to be fixed?:



### Screenshot:🔴mandatory 



### Conditions check:
<!-- check the contions
[x] will be counted as marked 
[ ] will be counted as marked 
-->

- [ ] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md#rules-for-fixing-bugs)

- [ ] i am sure, this issue is not raised before.

- [ ] i will try to do fix the bug properly.
