name: 💡Feature Request
description: Create a feature request issue
title: "[FEATURE]: <your-issue-title>"
labels: ["feature", "hacktoberfest", "hacktoberfest-accepted"]
body:
  - type: markdown
    attributes:
      value: "## Hello Welcome to QuoteVerse issue section!"

  - type: textarea
    id: reason
    attributes:
      label: Description
      description: A brief description of the feature, also include what you trying?
      placeholder: Tell us what you found
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots.
      description: Please add screenshots if applicable

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Fill up the boxes carefully.
      options:
        - label: i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
          required: true
        - label: "I checked and didn't find similar issue"
          required: true

  - type: dropdown
    attributes:
      label: Are you willing to work on this issue ?
      description: This is absolutely not required, but we are happy to guide you in the contribution process.
      options:
        - "Yes I am willing to submit a PR!"

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug! 
        Please give a ⭐ star to the repository
        Join us in github https://github.com/Shariar-Hasan
